name: Testes unitários
on:
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - 'FoodMinder/**'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: foodminder
          MYSQL_USER: projetos
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup - Projeto
        uses: actions/checkout@v3
      - name: Setup - RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '3000:3000 15672:15672'
          certificates: ${{ github.workspace }}/.ci/tls-certificates
          config: ${{ github.workspace }}/.ci/rabbitmq.conf
          definitions: ${{ github.workspace }}/.ci/definitions.json
          container-name: 'rabbitmq'
      - name: Setup - JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'
      - name: Iniciando teste
        run: mvn -B package --file FoodMinder/pom.xml